# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
# Version of the packaged app
appVersion: v0.4.0
# Make sure your name DOES NOT end in "app" or "-app".
name: envoy-ai-gateway
# Please describe what the app provides in a sentence or two.
description: The Helm chart for Envoy AI Gateway
# URL of the GitHub repository that is the source of this Chart.yaml file.
home: https://github.com/giantswarm/envoy-ai-gateway-app
icon: https://s.giantswarm.io/app-icons/envoy-ai-gateway/1/light.svg
keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg
  - ai-gateway
  - ai
sources:
  - https://github.com/envoyproxy/ai-gateway
type: application
version: 0.1.0
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: cabbage
