# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2

# Version of the packaged app
appVersion: v0.4.0

# Make sure your name DOES NOT end in "app" or "-app".
name: envoy-ai-gateway

# Please describe what the app provides in a sentence or two.
description: The Helm chart for Envoy AI Gateway

# URL of the GitHub repository that is the source of this Chart.yaml file.
home: https://github.com/giantswarm/envoy-ai-gateway-app

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
icon: https://raw.githubusercontent.com/envoyproxy/ai-gateway/refs/heads/main/site/static/img/logo.svg
keywords:
- gateway-api
- envoyproxy
- envoy-gateway
- eg
- ai-gateway
- ai

sources:
- https://github.com/envoyproxy/ai-gateway
type: application
version: 0.0.0-dev
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: cabbage
